services:
  lsp-ws-proxy:
    image: lsp-ws-proxy:latest
    ports:
      - "9999:9999"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      lsp_network:
        ipv4_address: 192.168.88.89
        aliases:
          - lsp-ws-proxy
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      lsp_network:
        ipv4_address: 192.168.88.88
        aliases:
          - lsp-mysql
    restart: always


networks:
  lsp_network:
    driver: bridge